sonar.host.url=https://sonarcloud.io

sonar.sources=central-perk/src,nexus/src,shelf-awareness/src
sonar.tests=central-perk/tests,nexus/tests,shelf-awareness/tests
sonar.javascript.lcov.reportPaths=central-perk/coverage/lcov.info,nexus/coverage/lcov.info,shelf-awareness/coverage/lcov.info
sonar.coverage.exclusions=**/tests/**,**/test/**,**/*.test.*,**/*.spec.*
sonar.exclusions=**/node_modules/**,**/.next/**,**/build/**,**/coverage/**
